name: nrbtv
description: "A new Flutter project."
publish_to: "none"
version: 1.0.1+3

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  commons:
    path: packages/commons

  ui_kit:
    path: packages/ui_kit

  app_logger:
    path: packages/app_logger

  app_localization:
    path: packages/app_localization

  app_focus:
    path: packages/app_focus

  local_storage:
    path: packages/local_storage
  flutter_native_splash: ^2.3.10

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3
  transparent_image: ^2.0.1
  cached_network_image: ^3.2.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: 0.19.0
  flutter_cache_manager: ^3.3.1
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  wakelock_plus: ^1.2.10
  bloc_concurrency: ^0.2.5
  stream_transform: ^2.1.0
  http: ^1.1.0
  image_picker: ^1.0.7
  ensure_visible_when_focused: ^1.1.1
  river_player: ^0.1.3
  shimmer: ^3.0.0
  qr_flutter: ^4.1.0
  flutter_inapp_purchase: ^5.6.1
  in_app_purchase: ^3.2.0
  equatable: ^2.0.5
  url_launcher: ^6.3.1

flutter_native_splash:
  android: true
  ios: true
  color: "#000000"

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  freezed: ^2.4.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/img/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-SemiBold.ttf
