name: commons
description: A new Flutter package project.
version: 0.0.1
publish_to: none
environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  # firebase_crashlytics: ^3.3.3
  # firebase_messaging: ^14.6.4
  flutter:
    sdk: flutter
  # flutter_local_notifications: ^16.3.2
  # firebase_core: ^2.14.0
  # firebase_remote_config: ^4.2.3
  path_provider: ^2.0.15
  app_logger:
    path: ../app_logger
  http: ^1.1.0
  
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  nrbtv:
    path: ../..
  local_storage:
    path: ../local_storage
  intl: 0.19.0
  equatable: ^2.0.5

  ui_kit:
    path: ../ui_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  freezed: ^2.4.1
  firebase_analytics: ^10.4.3
