name: app_localization
description: Provides internationalization and localization facilities, Depends On GetDataFromLocalStorageUseCase and SetDataFromseCase
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  local_storage:
    path: ../local_storage
  flutter_localizations:
    sdk: flutter

  intl: 0.19.0

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  freezed: ^2.4.1

flutter:
  generate: true
